#!/bin/bash

#file=$1
file="assignment1.md"
name="stephen-harris"

pandoc --standalone "$file" -o "${file%.*}-$name.pdf" -V "geometry:margin=1in" -c "https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.1.0/github-markdown.min.css"
